# Generated by Django 4.1.1 on 2022-09-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toy_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='ip',
        ),
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.EmailField(default='a@mail.tu', max_length=254),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(default='a', max_length=100, verbose_name='Имя'),
        ),
    ]
