# Generated by Django 4.1.1 on 2022-10-06 08:36

import app_toy_shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toy_shop', '0002_review_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[app_toy_shop.validators.phone_validator], verbose_name='телефон'),
        ),
    ]
