# Generated by Django 4.1.1 on 2022-10-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_toy_shop', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
